all:
  children:
    proxmox_servers:
      hosts:
        pve01:
          ansible_host: 192.168.2.77  # <--- Setze hier die IP-Adresse deines Proxmox-Servers ein
          ansible_user: admin
          