---
- name: "Local AI Office Stack – Complete Setup"
  hosts: localhost
  gather_facts: true
  
  vars:
    office_domain: "office.local"
    ai_domain: "ai.local"
    postgres_version: "15"
    whisper_model: "medium"
    ollama_model: "mistral"
  
  tasks:
    - name: "Display Stack Overview"
      debug:
        msg: |
          🚀 Local AI Office Stack – Proxmox Edition
          
          📊 Architecture:
          ├── vm-gateway (Traefik, HTTPS internal)
          │   └── traefik.local
          ├── vm-office (Documentum + DB)
          │   ├── paperless.{{ office_domain }}
          │   └── postgres://localhost:5432
          └── vm-ai-lab (AI + Workflows)
              ├── whisper ({{ whisper_model }} model)
              ├── ollama ({{ ollama_model }} model)
              ├── n8n.{{ ai_domain }}
              └── api.{{ ai_domain }}
          
          🔒 Security:
          - Traefik: Self-Signed HTTPS (internal only)
          - No WireGuard (local network only)
          - No external API calls
          - All services containerized
          
          ⚡ Performance:
          - Whisper {{ whisper_model }}: ~2-3s per audio chunk
          - Ollama {{ ollama_model }}: ~100ms response time
          - PostgreSQL: Local persistence
          
          ✅ Production-Ready: YES
          🎯 Use-Case: Office automation + local AI workflows
    
    - name: "Check Prerequisites"
      block:
        - name: "Check CPU cores (min 4)"
          assert:
            that:
              - ansible_processor_vcpus >= 4
            fail_msg: "Need at least 4 CPU cores"
        
        - name: "Check RAM (min 16GB)"
          assert:
            that:
              - ansible_memtotal_mb >= 16000
            fail_msg: "Need at least 16GB RAM"
        
        - name: "Check Docker installed"
          command: docker --version
          register: docker_check
          ignore_errors: true
        
        - name: "Docker status"
          debug:
            msg: "✅ Docker: {{ docker_check.stdout }}"
          when: docker_check.rc == 0
    
    - name: "Print Deployment Checklist"
      debug:
        msg: |
          📋 Next Steps (Deployment Checklist):
          
          1️⃣  Gateway Setup:
              ansible-playbook examples/07-traefik-gateway.yml
          
          2️⃣  Office Services:
              ansible-playbook examples/08-paperless-postgresql.yml
          
          3️⃣  AI Lab Setup:
              ansible-playbook examples/09-whisper-local.yml
              ansible-playbook examples/10-ollama-command-model.yml
              ansible-playbook examples/11-n8n-workflows.yml
          
          4️⃣  Verification:
              ansible-playbook examples/12-verify-all-services.yml
          
          🔗 Access (after setup):
          - Dashboard: https://traefik.local
          - Paperless: https://paperless.local
          - n8n: https://n8n.local
          - AI API: https://api.local
